/* Whimsy Workshop — markets & events. Generated by admin.html. */
window.WW_DEFAULT_EVENTS = [
 {
  "mon": "Aug",
  "day": "08",
  "name": "Pop-Up on Pelissier",
  "place": "530 Pelissier St, Windsor",
  "time": "Sat · 9am – 4pm",
  "soon": true
 },
 {
  "mon": "Apr",
  "day": "26",
  "name": "Family Fun Spring Market",
  "place": "970 Front Rd, LaSalle",
  "time": "Sun · 10am – 3pm",
  "soon": false
 },
 {
  "mon": "Feb",
  "day": "08",
  "name": "Womenpreneur's Ramadan Market",
  "place": "8787 McHugh St, Windsor",
  "time": "Sun · 12pm – 6pm",
  "soon": false
 },
 {
  "mon": "Jul",
  "day": "18",
  "name": "Windsor Spring Market",
  "place": "7515 Forest Glade Dr",
  "time": "Sat · 11am – 8:30pm",
  "soon": false
 }
];
