/* Whimsy Workshop — product store
   Source of truth for products + categories, shared by shop.html and admin.html.
   Reads defaults from products.js (window.WW_DEFAULT_PRODUCTS). Any admin edits are
   saved to localStorage under 'ww_products' and override the defaults in this browser.
   Use admin.html → "Download products.js" to make edits permanent on the live site. */
(function () {
  "use strict";
  var KEY = "ww_products";
  var KEYV = "ww_products_v";
  var VER = String(window.WW_CATALOG_VERSION || 0);

  /* preferred display order; anything else is appended in first-seen order */
  var CAT_ORDER = ["Bracelets", "Keychains", "Beadwork", "Necklaces", "Sets", "Earrings",
                   "Clay", "Crochet", "Felt"];
  var SUB_ORDER = {
    "Bracelets": ["Bracelets", "Floral", "Wire wrap", "Custom", "Loom"],
    "Clay": ["Clay", "Miniature"],
    "Crochet": ["Plush", "Bags", "Clothing", "Decor", "Coasters", "Blankets"],
  };

  function defaults() {
    return (window.WW_DEFAULT_PRODUCTS || []).map(function (p) { return Object.assign({}, p); });
  }
  function all() {
    try {
      if (localStorage.getItem(KEYV) === VER) {
        var s = localStorage.getItem(KEY); if (s) return JSON.parse(s);
      }
    } catch (e) {}
    return defaults();
  }
  function save(list) {
    try { localStorage.setItem(KEY, JSON.stringify(list)); localStorage.setItem(KEYV, VER); return true; }
    catch (e) { return false; }
  }
  function upsert(prod) {
    var list = all();
    var i = list.findIndex(function (p) { return p.id === prod.id; });
    if (i >= 0) list[i] = prod; else list.push(prod);
    return save(list);
  }
  function remove(id) { return save(all().filter(function (p) { return p.id !== id; })); }
  function reset() { try { localStorage.removeItem(KEY); localStorage.removeItem(KEYV); } catch (e) {} }
  function isCustomized() { try { return localStorage.getItem(KEYV) === VER && !!localStorage.getItem(KEY); } catch (e) { return false; } }

  function ordered(values, order) {
    var seen = {}, out = [];
    (order || []).forEach(function (v) { if (values.indexOf(v) >= 0) { out.push(v); seen[v] = 1; } });
    values.forEach(function (v) { if (!seen[v]) { out.push(v); seen[v] = 1; } });
    return out;
  }
  function categories() {
    var list = all(), vals = [];
    list.forEach(function (p) { if (p.category && vals.indexOf(p.category) < 0) vals.push(p.category); });
    return ordered(vals, CAT_ORDER);
  }
  function subs(cat) {
    var list = all(), vals = [];
    list.forEach(function (p) { if (p.category === cat && p.sub && vals.indexOf(p.sub) < 0) vals.push(p.sub); });
    return ordered(vals, SUB_ORDER[cat]);
  }
  function newId(name) {
    return (name || "item").toLowerCase().replace(/[^a-z0-9]+/g, "-").replace(/^-|-$/g, "")
      + "-" + Date.now().toString(36);
  }
  function exportFileText() {
    var header = "/* Whimsy Workshop — product catalog. Generated by admin.html. */\n";
    return header + "window.WW_CATALOG_VERSION = " + VER + ";\n"
      + "window.WW_DEFAULT_PRODUCTS = " + JSON.stringify(all(), null, 1) + ";\n";
  }

  /* ---- markets & events ---- */
  var EKEY = "ww_events";
  function events() {
    try { var s = localStorage.getItem(EKEY); if (s) return JSON.parse(s); } catch (e) {}
    return (window.WW_DEFAULT_EVENTS || []).map(function (x) { return Object.assign({}, x); });
  }
  function saveEvents(list) {
    try { localStorage.setItem(EKEY, JSON.stringify(list)); return true; } catch (e) { return false; }
  }
  function resetEvents() { try { localStorage.removeItem(EKEY); } catch (e) {} }
  function eventsCustomized() { try { return !!localStorage.getItem(EKEY); } catch (e) { return false; } }
  function exportEventsText() {
    return "/* Whimsy Workshop — markets & events. Generated by admin.html. */\n"
      + "window.WW_DEFAULT_EVENTS = " + JSON.stringify(events(), null, 1) + ";\n";
  }

  /* ---- testimonials ---- */
  var TKEY = "ww_testimonials";
  function testimonials() {
    try { var s = localStorage.getItem(TKEY); if (s) return JSON.parse(s); } catch (e) {}
    return (window.WW_DEFAULT_TESTIMONIALS || []).map(function (x) { return Object.assign({}, x); });
  }
  function saveTestimonials(list) {
    try { localStorage.setItem(TKEY, JSON.stringify(list)); return true; } catch (e) { return false; }
  }
  function resetTestimonials() { try { localStorage.removeItem(TKEY); } catch (e) {} }
  function testimonialsCustomized() { try { return !!localStorage.getItem(TKEY); } catch (e) { return false; } }
  function exportTestimonialsText() {
    return "/* Whimsy Workshop — testimonials. Generated by admin.html. */\n"
      + "window.WW_DEFAULT_TESTIMONIALS = " + JSON.stringify(testimonials(), null, 1) + ";\n";
  }

  /* ---- page settings (About photo, etc.) ---- */
  var SKEY = "ww_about_img";
  function aboutImage() {
    try { var s = localStorage.getItem(SKEY); if (s !== null) return s; } catch (e) {}
    return (window.WW_SETTINGS && window.WW_SETTINGS.aboutImage) || "";
  }
  function setAboutImage(d) { try { localStorage.setItem(SKEY, d); return true; } catch (e) { return false; } }
  function resetAboutImage() { try { localStorage.removeItem(SKEY); } catch (e) {} }
  function exportSettingsText() {
    return "/* Whimsy Workshop — page settings. Generated by admin.html. */\n"
      + "window.WW_SETTINGS = " + JSON.stringify({ aboutImage: aboutImage() }, null, 1) + ";\n";
  }

  window.WWStore = {
    all: all, save: save, upsert: upsert, remove: remove, reset: reset,
    isCustomized: isCustomized, defaults: defaults,
    categories: categories, subs: subs, newId: newId,
    exportFileText: exportFileText,
    CAT_ORDER: CAT_ORDER,
    events: events, saveEvents: saveEvents, resetEvents: resetEvents,
    eventsCustomized: eventsCustomized, exportEventsText: exportEventsText,
    aboutImage: aboutImage, setAboutImage: setAboutImage, resetAboutImage: resetAboutImage,
    exportSettingsText: exportSettingsText,
    testimonials: testimonials, saveTestimonials: saveTestimonials, resetTestimonials: resetTestimonials,
    testimonialsCustomized: testimonialsCustomized, exportTestimonialsText: exportTestimonialsText
  };
})();
